
package org.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaxServiceImpl", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaxServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compute", targetNamespace = "http://example.org/", className = "org.example.Compute")
    @ResponseWrapper(localName = "computeResponse", targetNamespace = "http://example.org/", className = "org.example.ComputeResponse")
    @Action(input = "http://example.org/TaxServiceImpl/computeRequest", output = "http://example.org/TaxServiceImpl/computeResponse")
    public double compute(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTax", targetNamespace = "http://example.org/", className = "org.example.GetTax")
    @ResponseWrapper(localName = "getTaxResponse", targetNamespace = "http://example.org/", className = "org.example.GetTaxResponse")
    @Action(input = "http://example.org/TaxServiceImpl/getTaxRequest", output = "http://example.org/TaxServiceImpl/getTaxResponse")
    public double getTax(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
